name: GitHub Actions CI-CD-MAIN
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  # Trigger automatically on pushes to specific branches
  push:
    branches:
      - main
  # Trigger manually with custom configuration inputs
  workflow_dispatch:

jobs:
  Build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: echo "Building Application.."

  Test-Cases:
    runs-on: self-hosted
    needs: Build
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: echo "Building Application"

  Dev-Deploy:
    runs-on: self-hosted
    needs: Test-Cases
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: echo "Building Application"

  QA-Deploy:
    runs-on: self-hosted
    needs: Dev-Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: echo "Building Application"

## at this stage we hwill be having End to End to test cases and performance test case based on the project or may be the UAT and prod runs on a different pipeline

  UAT-Deplpy:
    runs-on: self-hosted
    needs: QA-Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: echo "Building Application"

  Prod-Deploy:
    runs-on: self-hosted
    needs: UAT-Deplpy
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: echo "Building Application"