##push trigger

name: Example5
on: [push]
jobs:
  test1:
    runs-on: self-hosted
    steps:
      - run: |
          echo "{Terraform apply}" >> $GITHUB_STEP_SUMMARY
#          echo "::error Intentional error ::Missing semicolon"
#          exit 1
