##push trigger

name: Example7
on: [push]
jobs:
  test1:
    runs-on: self-hosted
    steps:
      - name: Failing step
        id: demo
        continue-on-error: true
        run: exit 1

      - name: The demo step has failed
        if: ${{ steps.demo.outcome == 'failure' }}
        run: echo "demo step has failed" >> $GITHUB_STEP_SUMMARY